language: go

go:
  - 1.8

os: linux
dist: trusty
sudo: required
env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows

script:
  - env GOARCH=${BUILD_GOARCH} GOOS=${BUILD_GOOS} go build -o ${GOPATH}/bin/hello-${BUILD_GOOS}-${BUILD_GOARCH}
  - if [[ "$BUILD_GOOS" == "linux" ]]; then hello-${BUILD_GOOS}-${BUILD_GOARCH} Odaceo ; fi

deploy:
  provider: bintray
  file: bintray.json
  user: ${BINTRAY_USER}
  key: ${BINTRAY_PASS}
